c11_uleague/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('manage_pertandingan/', include('manage_pertandingan.urls')),
    path('list_pertandingan/', include('list_pertandingan.urls')),
    path('history_rapat/', include('history_rapat.urls')),
    path('pembuatan_pertandingan/', include('pembuatan_pertandingan.urls')),
    path('peminjaman_stadium/', include('peminjaman_stadium.urls')),
    path('pembelian_tiket/', include('pembelian_tiket.urls')),
    path('mulai_rapat/', include('mulai_rapat.urls')),
    path('mengelola_tim/', include('mengelola_tim.urls')),
    path('user_dashboard/', include('user_dashboard.urls')),
]

home/urls.py
from django.urls import path
from home.views import *

app_name = 'home'

urlpatterns = [
    path('', home, name='home'),
    path('login_register/', login_register, name='login_register'),
    path('register/', register, name='register'),
    path('register_manajer/', register_manajer, name='register_manajer'),
    path('register_penonton/', register_penonton, name='register_penonton'),
    path('register_panitia/', register_panitia, name='register_panitia'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
]

pembelian_tiket/urls.py
from django.urls import path
from pembelian_tiket.views import *

app_name = 'pembelian_tiket'

urlpatterns = [
    path('', pilih_stadium_tiket, name='pilih_stadium_tiket'),
    path('list_waktu_stadium/', list_waktu_stadium_tiket, name='list_waktu_stadium_tiket'),
    path('list_pertandingan/<str:waktu>/<str:stadium>/', list_pertandingan_tiket, name="list_pertandingan_tiket"),
    path('beli_tiket/<str:id_pertandingan>/', pembelian_tiket, name="pembelian_tiket")
    

]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from utils.query import query
import uuid

# Create your views here.
# @login_required(login_url='/login_register/')
def home(request):
    role = request.COOKIES.get("role")

    context = {
        'role': role
    }
    return render(request, 'home.html', context)


@csrf_exempt
def login_register(request):
    return render(request, 'login_register.html')

def register(request):
   
    return render(request, 'register.html')

def register_manajer(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        nama_depan = request.POST.get("nama_depan")
        nama_belakang = request.POST.get("nama_belakang")
        nomor_hp = request.POST.get("telp")
        email = request.POST.get("email")
        alamat = request.POST.get("alamat")
        role = request.POST.get("role")
        id = str(uuid.uuid4())

        print([username, password, nama_depan, nama_belakang, nomor_hp, email, alamat, role, id])
        
        
        ins_user_system, err1 = query(f"insert into user_system(username,password) values ('{username}', '{password}')")
        if err1 != None:
            e = str(err1).split('\n')[0]
            print(e)
            context = {
                "role": role,
                "messages": e,
            }
            return render(request, 'register_manajer.html', context)

        
        ins_non_pemain, err = query(f"insert into non_pemain(id,nama_depan,nama_belakang,nomor_hp,email,alamat) values ('{id}', '{nama_depan}', '{nama_belakang}','{nomor_hp}', '{email}','{alamat}')")
        ins_status_non_pemain, err = query(f"insert into status_non_pemain(id_non_pemain,status) values ('{id}', '{role}')")
        ins_manajer, err = query(f"insert into manajer(id_manajer ,username) values ('{id}', '{username}')")

        
       

        messages.success(request, "Berhasil mendaftar sebagai manajer!")
        return redirect("home:login")
            
        

    return render(request, "register_manajer.html")

def register_penonton(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        nama_depan = request.POST.get("nama_depan")
        nama_belakang = request.POST.get("nama_belakang")
        nomor_hp = request.POST.get("telp")
        email = request.POST.get("email")
        alamat = request.POST.get("alamat")
        role = request.POST.get("role")
        id = str(uuid.uuid4())

        print([username, password, nama_depan, nama_belakang, nomor_hp, email, alamat, role, id])
        
        try:
            ins_user_system, err = query(f"insert into user_system(username,password) values ('{username}', '{password}')")
            ins_non_pemain, err = query(f"insert into non_pemain(id,nama_depan,nama_belakang,nomor_hp,email,alamat) values ('{id}', '{nama_depan}', '{nama_belakang}','{nomor_hp}', '{email}','{alamat}')")
            ins_status_non_pemain, err = query(f"insert into status_non_pemain(id_non_pemain,status) values ('{id}', '{role}')")
            ins_penonton, err = query(f"insert into penonton(id_penonton ,username) values ('{id}', '{username}')")
        
            messages.success(request, "Berhasil mendaftar sebagai penonton!")
            return redirect("home:login")
            
        except Exception as e:
            messages.error(request, e)
            
    return render(request, "register_penonton.html")

def register_panitia(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        nama_depan = request.POST.get("nama_depan")
        nama_belakang = request.POST.get("nama_belakang")
        nomor_hp = request.POST.get("telp")
        email = request.POST.get("email")
        alamat = request.POST.get("alamat")
        role = request.POST.get("role")
        id = str(uuid.uuid4())
        jabatan = request.POST.get("jabatan")
        print([username, password, nama_depan, nama_belakang, nomor_hp, email, alamat, role, id, jabatan])
        
        try:
            ins_user_system, err = query(f"insert into user_system(username,password) values ('{username}', '{password}')")
            ins_non_pemain, err = query(f"insert into non_pemain(id,nama_depan,nama_belakang,nomor_hp,email,alamat) values ('{id}', '{nama_depan}', '{nama_belakang}','{nomor_hp}', '{email}','{alamat}')")
            ins_status_non_pemain, err = query(f"insert into status_non_pemain(id_non_pemain,status) values ('{id}', '{role}')")

            q4 =f"insert into panitia(id_panitia, jabatan ,username) values ('{id}', '{jabatan}', '{username}')"
            ins_panitia, err = query(q4)
            print(q4)

            messages.success(request, "Berhasil mendaftar sebagai panitia!")
            return redirect("home:login")
            
        except Exception as e:
            messages.error(request, e)
            
    return render(request, "register_panitia.html")




@csrf_exempt
def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user_id = None

       
       
        get_user = query(f"select * from user_system where username = '{username}' and password = '{password}'")
        # print(len(get_user[0]) == 0)
        # print(get_user)
        # print(get_user[0][0][0])


        if len(get_user[0]) != 0:
            role = None

            #Check manajer
            get_role = query(f"select * from manajer where username = '{username}'")
            # print(get_role)
            role = "MANAJER"
            
            

            if len(get_role[0]) == 0:

                #Check panitia
                get_role = query(f"select * from panitia where username = '{username}'")
                role = "PANITIA"
                if len(get_role[0]) == 0:

                    #Check penonton
                    get_role = query(f"select * from penonton where username = '{username}'")
                    role  = "PENONTON"   

                     
            
            user_id = get_role[0][0][0]
            print(user_id)
            context = {
                'username': username,
                'password': password,
                'role': role,
            }
            
            
            # print(role)
            response = render(request, 'home.html', context)
            response.set_cookie('role', role)
            response.set_cookie('username', username)
            response.set_cookie('userId', user_id)
            return response
            
        else:
            context = {
                'message': 'Cek kembali username dan password anda!',
                'status': 'error',
                'role': None,
            }
            return render(request, 'login1.html', context)

        
    context = {}
    return render(request, 'login1.html', context)

def logout_user(request):
    response = redirect(reverse('home:login'))
    for cookie in request.COOKIES:
        response.delete_cookie(cookie)
    return response

home/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>U-League</title>
{% endblock meta %}

{% block content %}
<div class="hero min-h-screen bg-base-200">
    <div class="hero-content flex-col lg:flex-row-reverse">
      <img src="/static/hero.png" class="max-w-sm rounded-lg shadow-2xl" width="300" height="auto"/>
      <div>
        <h1 class="text-5xl font-bold">U-League
            Indonesian Universities Football
            Championship</h1>
        <p class="py-6">Kementerian Pemuda dan Olahraga RI bekerja sama dengan Kementerian Pendidikan, Kebudayaan,
          Riset, dan Teknologi mengadakan U-League yaitu liga sepak bola antar universitas. U-League berlangsung
          selama 3 bulan dimana semua tim bertanding di babak penyisihan sampai didapatkan 32 tim yang
          melaju ke babak kualifikasi. 32 tim dibagi menjadi 8 grup. Dua pemenang di setiap grup maju ke 16
          besar dan seterusnya sampai didapatkan dua tim yang bertanding di babak final.</p>
        <button class="btn btn-primary">Get Started</button>
      </div>
    </div>
</div>
{% endblock content %}

home/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class="flex justify-center p-16">
    <h1 class="text-4xl font-bold">
        FORM LOGIN
    </h1>
</div>

<div class="overflow-x-auto px-8 py-4"
    style="margin: 0 auto; width: fit-content; border: 1px solid white; border-radius: 10px;">
    <form method="post" action="{% url 'home:login' %}">
        {% csrf_token %}
        <div class="gap-5 text-left grid grid-cols-3 grid-rows-2 items-center">
           
            <label for="username">Username:</label>
            <input type="text" name="username" id="username" placeholder="Isi username" required
                class="col-span-2 block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" />
            <label for="password">Password:</label>
            <input type="password" name="password" id="password" placeholder="Isi password" required
                class="col-span-2 block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" />


            <div class="col-span-3 flex justify-center">
                <input class="text-white font-regular py-2 px-4 rounded-md text-center" type="submit" value="LOGIN"
                    style="background-color: #38404e;" />
            </div>


        </div>
        {% if message %} 
        <div class="mt-2 text-{{ message.tags }} text-sm text-center">{{ message }}</div>
        {% endif %}

        <br>

        <p class="text-center">
            Belum mempunyai akun?
            <a href="{% url 'home:register' %}" class="font-bold text-green underline hover:no-underline">Register</a>
        </p>
        
    </form>

</div>

<br>
<!-- 
<div class="flex justify-center">
    <form action="{% url 'pembelian_tiket:list_waktu_stadium_tiket' %}" method="POST">
        {% csrf_token %}
    </form>
    
</div> -->

<br>

{% endblock content %}

home/templates/login_register.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Login and Register</title>
{% endblock meta %}

{% block content %}

<div class="hero min-h-screen bg-base-200">
    <div class="hero-content flex-col lg:flex-row-reverse">
      <div>
        <h1 class="text-5xl font-bold">BABADU - C11</h1>
        <button class="btn btn-primary" type="button"><a href="{% url 'home:login' %}">LOGIN</a></button>
        <button class="btn btn-primary" type="button"><a href="{% url 'home:register' %}">REGISTER</a></button>
      </div>
    </div>
</div>
{% endblock content %}

home/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi</title>
{% endblock meta %}

{% block content %}  

<div class="flex justify-center p-16">
    <h1 class="text-4xl font-bold">
        FORM REGISTRASI
    </h1>
</div>

<div class="overflow-x-auto px-8 py-4" style="margin: 0 auto; width: fit-content; border: 1px solid white; border-radius: 10px;">
    <a class="text-white font-regular py-2 px-4 rounded-md" style="background-color: #38404e;" href="{% url 'home:register_manajer' %}">Manajer</a>
    <a class="text-white font-regular py-2 px-4 rounded-md" style="background-color: #38404e;" href="{% url 'home:register_penonton' %}">Penonton</a>
    <a class="text-white font-regular py-2 px-4 rounded-md" style="background-color: #38404e;" href="{% url 'home:register_panitia' %}">Panitia</a>

</div>

<br>
<!-- 
<div class="flex justify-center">
    <form action="{% url 'pembelian_tiket:list_waktu_stadium_tiket' %}" method="POST">
        {% csrf_token %}
    </form>
    
</div> -->

<br>

{% endblock content %}

home/templates/register_manajer.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Manajer</title>
{% endblock meta %}

{% block content %}

<div class="flex justify-center p-16">
    <h1 class="text-4xl font-bold">
        FORM REGISTRASI
    </h1>
</div>

<div class="overflow-x-auto px-8 py-4"
    style="margin: 0 auto; width: fit-content; border: 1px solid white; border-radius: 10px;">
    <form method="post" action="{% url 'home:register_manajer' %}">
        {% csrf_token %}
        <div class="gap-5 text-left grid grid-cols-3 grid-rows-2 items-center">
            <label for="email">Email:</label>
            <input type="email" name="email" id="email" placeholder="Isi email" required
                class="col-span-2 block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" />

            <label for="username">Username:</label>
            <input type="text" name="username" id="username" placeholder="Isi username" required
                class="col-span-2 block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" />
            <label for="password">Password:</label>
            <input type="password" name="password" id="password" placeholder="Isi password" required
                class="col-span-2 block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" />


            <label for="nama_depan">Nama Depan:</label>
            <input type="text" name="nama_depan" id="nama_depan" placeholder="Isi nama depan" required
                class="col-span-2 block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" />
            <label for="nama_belakang">Nama Belakang:</label>
            <input type="text" name="nama_belakang" id="nama_belakang" placeholder="Isi nama belakang" required
                class="col-span-2 block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" />
            <label for="telp">Nomor HP:</label>
            <input type="tel" name="telp" id="telp" placeholder="Isi nomor HP" required
                class="col-span-2 block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" />

            <label for="alamat">Alamat:</label>
            <input type="text" name="alamat" id="alamat" placeholder="Isi alamat" required
                class="col-span-2 block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" />


            <label for="role">Status:</label>
            <div class="col-span-2">
                <label class="inline-flex items-center">
                    <input type="radio" name="role" value="mahasiswa" required>
                    <span class="ml-2">Mahasiswa</span>
                </label>
                <label class="inline-flex items-center">
                    <input type="radio" name="role" value="dosen" required>
                    <span class="ml-2">Dosen</span>
                </label>
                <label class="inline-flex items-center">
                    <input type="radio" name="role" value="tendik" required>
                    <span class="ml-2">Tendik</span>
                </label>
                <label class="inline-flex items-center">
                    <input type="radio" name="role" value="alumni" required>
                    <span class="ml-2">Alumni</span>
                </label>
                <label class="inline-flex items-center">
                    <input type="radio" name="role" value="umum" required>
                    <span class="ml-2">Umum</span>
                </label>
            </div>

            <br>
            {% if messages %}
            <div class="text-red-500 mt-4">

                <p>{{ messages }}</p>

            </div>
            {% endif %}
            <div class="col-span-3 flex justify-center">
                <input class="text-white font-regular py-2 px-4 rounded-md text-center" type="submit" value="DAFTAR"
                    style="background-color: #38404e;" />
            </div>

            <br>

        </div>
        <p class="text-center">
            Sudah mempunyai akun?
            <a href="{% url 'home:login' %}" class="font-bold text-green underline hover:no-underline">Login</a>
        </p>


    </form>


</div>

<br>
<!-- 
<div class="flex justify-center">
    <form action="{% url 'pembelian_tiket:list_waktu_stadium_tiket' %}" method="POST">
        {% csrf_token %}
    </form>
    
</div> -->

<br>

{% endblock content %}

home/templates/register_panitia.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Penonton</title>
{% endblock meta %}

{% block content %}

<div class="flex justify-center p-16">
    <h1 class="text-4xl font-bold">
        FORM REGISTRASI
    </h1>
</div>

<div class="overflow-x-auto px-8 py-4"
    style="margin: 0 auto; width: fit-content; border: 1px solid white; border-radius: 10px;">
    <form method="post" action="{% url 'home:register_panitia' %}">
        {% csrf_token %}
        <div class="gap-5 text-left grid grid-cols-3 grid-rows-2 items-center">
            <label for="email">Email:</label>
            <input type="email" name="email" id="email" placeholder="Isi email" required
                class="col-span-2 block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" />

            <label for="username">Username:</label>
            <input type="text" name="username" id="username" placeholder="Isi username" required
                class="col-span-2 block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" />
            <label for="password">Password:</label>
            <input type="password" name="password" id="password" placeholder="Isi password" required
                class="col-span-2 block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" />


            <label for="nama_depan">Nama Depan:</label>
            <input type="text" name="nama_depan" id="nama_depan" placeholder="Isi nama depan" required
                class="col-span-2 block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" />
            <label for="nama_belakang">Nama Belakang:</label>
            <input type="text" name="nama_belakang" id="nama_belakang" placeholder="Isi nama belakang" required
                class="col-span-2 block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" />
            <label for="telp">Nomor HP:</label>
            <input type="tel" name="telp" id="telp" placeholder="Isi nomor HP" required
                class="col-span-2 block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" />

            <label for="alamat">Alamat:</label>
            <input type="text" name="alamat" id="alamat" placeholder="Isi alamat" required
                class="col-span-2 block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" />
            
            <label for="jabatan">Jabatan:</label>
            <input type="text" name="jabatan" id="jabatan" placeholder="Isi jabatan" required
                class="col-span-2 block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" />
                

            <label for="role">Status:</label>
            <div class="col-span-2">
                <label class="inline-flex items-center">
                    <input type="radio" name="role" value="mahasiswa" required>
                    <span class="ml-2">Mahasiswa</span>
                </label>
                <label class="inline-flex items-center">
                    <input type="radio" name="role" value="dosen" required>
                    <span class="ml-2">Dosen</span>
                </label>
                <label class="inline-flex items-center">
                    <input type="radio" name="role" value="tendik" required>
                    <span class="ml-2">Tendik</span>
                </label>
                <label class="inline-flex items-center">
                    <input type="radio" name="role" value="alumni" required>
                    <span class="ml-2">Alumni</span>
                </label>
                <label class="inline-flex items-center">
                    <input type="radio" name="role" value="umum" required>
                    <span class="ml-2">Umum</span>
                </label>
            </div>

            <br>
            <div class="col-span-3 flex justify-center">
                <input class="text-white font-regular py-2 px-4 rounded-md text-center" type="submit" value="DAFTAR"
                    style="background-color: #38404e;" />
            </div>

            <br>

        </div>
        <p class="text-center">
            Sudah mempunyai akun?
            <a href="{% url 'home:login' %}" class="font-bold text-green underline hover:no-underline">Login</a>
        </p>
        {% if messages %} {% for message in messages %}
        <div class="mt-2 text-{{ message.tags }} text-sm text-center">{{ message }}</div>
        {% endfor %} {% endif %}
    </form>

</div>

<br>
<!-- 
<div class="flex justify-center">
    <form action="{% url 'pembelian_tiket:list_waktu_stadium_tiket' %}" method="POST">
        {% csrf_token %}
    </form>
    
</div> -->

<br>

{% endblock content %}

home/templates/register_penonton.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Penonton</title>
{% endblock meta %}

{% block content %}

<div class="flex justify-center p-16">
    <h1 class="text-4xl font-bold">
        FORM REGISTRASI
    </h1>
</div>

<div class="overflow-x-auto px-8 py-4"
    style="margin: 0 auto; width: fit-content; border: 1px solid white; border-radius: 10px;">
    <form method="post" action="{% url 'home:register_penonton' %}">
        {% csrf_token %}
        <div class="gap-5 text-left grid grid-cols-3 grid-rows-2 items-center">
            <label for="email">Email:</label>
            <input type="email" name="email" id="email" placeholder="Isi email" required
                class="col-span-2 block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" />

            <label for="username">Username:</label>
            <input type="text" name="username" id="username" placeholder="Isi username" required
                class="col-span-2 block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" />
            <label for="password">Password:</label>
            <input type="password" name="password" id="password" placeholder="Isi password" required
                class="col-span-2 block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" />


            <label for="nama_depan">Nama Depan:</label>
            <input type="text" name="nama_depan" id="nama_depan" placeholder="Isi nama depan" required
                class="col-span-2 block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" />
            <label for="nama_belakang">Nama Belakang:</label>
            <input type="text" name="nama_belakang" id="nama_belakang" placeholder="Isi nama belakang" required
                class="col-span-2 block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" />
            <label for="telp">Nomor HP:</label>
            <input type="tel" name="telp" id="telp" placeholder="Isi nomor HP" required
                class="col-span-2 block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" />

            <label for="alamat">Alamat:</label>
            <input type="text" name="alamat" id="alamat" placeholder="Isi alamat" required
                class="col-span-2 block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" />
            
            

            <label for="role">Status:</label>
            <div class="col-span-2">
                <label class="inline-flex items-center">
                    <input type="radio" name="role" value="mahasiswa" required>
                    <span class="ml-2">Mahasiswa</span>
                </label>
                <label class="inline-flex items-center">
                    <input type="radio" name="role" value="dosen" required>
                    <span class="ml-2">Dosen</span>
                </label>
                <label class="inline-flex items-center">
                    <input type="radio" name="role" value="tendik" required>
                    <span class="ml-2">Tendik</span>
                </label>
                <label class="inline-flex items-center">
                    <input type="radio" name="role" value="alumni" required>
                    <span class="ml-2">Alumni</span>
                </label>
                <label class="inline-flex items-center">
                    <input type="radio" name="role" value="umum" required>
                    <span class="ml-2">Umum</span>
                </label>
            </div>

            <br>
            <div class="col-span-3 flex justify-center">
                <input class="text-white font-regular py-2 px-4 rounded-md text-center" type="submit" value="DAFTAR"
                    style="background-color: #38404e;" />
            </div>

            <br>

        </div>
        <p class="text-center">
            Sudah mempunyai akun?
            <a href="{% url 'home:login' %}" class="font-bold text-green underline hover:no-underline">Login</a>
        </p>
        {% if messages %} {% for message in messages %}
        <div class="mt-2 text-{{ message.tags }} text-sm text-center">{{ message }}</div>
        {% endfor %} {% endif %}
    </form>

</div>

<br>
<!-- 
<div class="flex justify-center">
    <form action="{% url 'pembelian_tiket:list_waktu_stadium_tiket' %}" method="POST">
        {% csrf_token %}
    </form>
    
</div> -->

<br>

{% endblock content %}