c11_uleague/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('manage_pertandingan/', include('manage_pertandingan.urls')),
    path('list_pertandingan/', include('list_pertandingan.urls')),
    path('history_rapat/', include('history_rapat.urls')),
    path('pembuatan_pertandingan/', include('pembuatan_pertandingan.urls')),
    path('peminjaman_stadium/', include('peminjaman_stadium.urls')),
    path('pembelian_tiket/', include('pembelian_tiket.urls')),
    path('mulai_rapat/', include('mulai_rapat.urls')),
    path('mengelola_tim/', include('mengelola_tim.urls')),
    path('user_dashboard/', include('user_dashboard.urls')),
]

home/urls.py
from django.urls import path
from home.views import *

app_name = 'home'

urlpatterns = [
    path('', home, name='home'),
    path('login_register/', login_register, name='login_register'),
    path('register/', register, name='register'),
    path('register_manajer/', register_manajer, name='register_manajer'),
    path('register_penonton/', register_penonton, name='register_penonton'),
    path('register_panitia/', register_panitia, name='register_panitia'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
]

pembelian_tiket/urls.py
from django.urls import path
from pembelian_tiket.views import *

app_name = 'pembelian_tiket'

urlpatterns = [
    path('', pilih_stadium_tiket, name='pilih_stadium_tiket'),
    path('list_waktu_stadium/', list_waktu_stadium_tiket, name='list_waktu_stadium_tiket'),
    path('list_pertandingan/<str:waktu>/<str:stadium>/', list_pertandingan_tiket, name="list_pertandingan_tiket"),
    path('beli_tiket/<str:id_pertandingan>/', pembelian_tiket, name="pembelian_tiket")
    

]

pembelian_tiket/models.py
from django.db import models

# Create your models here.

pembelian_tiket/views.py
from django.shortcuts import redirect, render
from utils.query import query
import datetime
import re
from random import randint

alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
number = "0123456789"

# Create your views here.
def pembelian_tiket(request,id_pertandingan):
    role = request.COOKIES.get('role')

    if role == None:
        return redirect('home:login')
    if role not in ["PENONTON"]:
        return redirect('home:home')

    if request.method == 'POST':
        jenis_tiket = request.POST.get('jenis_tiket')
        pembayaran = request.POST.get('Pembayaran')
        
        #ubah kalo login udah diimplement
        id_penonton = request.COOKIES.get('userId')

        receipt_builder = ""

        
        receipt_builder += pembayaran[0]


        for i in range(7):
            check = randint(0,1)
            if check == 0:
                receipt_builder += alphabet[randint(0,25)]
            else: 
                receipt_builder += number[randint(0,9)]
        
        print([jenis_tiket,pembayaran,id_penonton,id_pertandingan])
        
        ins_pembelian_tiket, err = query(f"insert into pembelian_tiket(nomor_receipt,id_penonton, jenis_tiket, jenis_pembayaran, id_pertandingan) values ('{receipt_builder}','{id_penonton}', '{jenis_tiket}', '{pembayaran}', '{id_pertandingan}')")
       
        if err != None:
            e = str(err).split('\n')[0]
            print(e)
            context = {
                "role": role,
                "messages": e,
            }
            return render(request, 'pembelian_tiket.html', context)

       
            
        

      
        return redirect('home:home') 
   
    context = {
        "role": role
    }
        
    return render(request, 'pembelian_tiket.html', context)


def list_waktu_stadium_tiket(request):
    role = request.COOKIES.get('role')

    if role == None:
        return redirect('home:login')
    if role not in ["PENONTON"]:
        return redirect('home:home')

    if request.method == 'POST':
        
        stadium = request.POST.get('stadium')
        date = request.POST.get('date')
        
        list_pertandingan, err = query(f"Select p.start_datetime, p.end_datetime from pertandingan p where '{date}' = DATE(p.start_datetime) and p.stadium in (select p.stadium from pertandingan p, stadium s where p.stadium =  s.id_stadium and s.nama = '{stadium}')")
        print(list_pertandingan)
        
        get_time = None


        if type(list_pertandingan) == type(None):
            context = {
            'stadium': stadium,
            'date': get_time,

            'list_pertandingan' : None,
            'role': role
            }
            return render(request, 'list_waktu_stadium_tiket.html', context)
            
        if len(list_pertandingan) > 0:
            get_time = list_pertandingan[0][0].strftime("%Y-%m-%d %H:%M")
        

        clean_list_pertandingan = []
        
        for i in range(len(list_pertandingan)):
            clean_list_pertandingan.append([0,0])
            clean_list_pertandingan[i][0] = list_pertandingan[i][0].strftime("%H:%M")
            clean_list_pertandingan[i][1] = list_pertandingan[i][1].strftime("%H:%M")

        context = {
            'stadium': stadium,
            'date': get_time,

            'list_pertandingan' : clean_list_pertandingan,
            'role': role

        }
        return render(request, 'list_waktu_stadium_tiket.html', context)
    
    context = {
        'role': role
    }
    return render(request, 'list_waktu_stadium_tiket.html', context)



def list_pertandingan_tiket(request,waktu,stadium):
    role = request.COOKIES.get('role')

    if role == None:
        return redirect('home:login')
    if role not in ["PENONTON"]:
        return redirect('home:home')

    id_pertandingan, err = query(f"select id_pertandingan from pertandingan where start_datetime='{waktu}' and stadium=(select p.stadium from pertandingan p, stadium s where p.stadium = s.id_stadium and s.nama = '{stadium}')")
    id_pertandingan = str(id_pertandingan[0][0])
    print(id_pertandingan)
    tim_bertanding, err = query(f"select distinct tm.nama_tim from tim_pertandingan tm, pertandingan p where tm.id_pertandingan = '{str(id_pertandingan)}'" )
    print(tim_bertanding)
    tim_bertanding = [tim_bertanding[0][0], tim_bertanding[1][0]]

    context = {
        'tim_bertanding' : tim_bertanding,
        'id_pertandingan' : id_pertandingan,
        'role' : role
    }
    return render(request, 'list_pertandingan_tiket.html',context)


def pilih_stadium_tiket(request):
    role = request.COOKIES.get('role')

    if role == None:
        return redirect('home:login')
    if role not in ["PENONTON"]:
        return redirect('home:home')
    
    list_stadium, err = query("select nama from stadium")
   
    for i in range(len(list_stadium)):
        list_stadium[i] = list_stadium[i][0]
    
    context = {
        "list_stadium" : list_stadium,
        "role": role

    }

    print(list_stadium)
   
    return render(request, 'pilih_stadium_tiket.html', context)

pembelian_tiket/templates/list_pertandingan_tiket.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>List Pertandingan</title>

{% endblock meta %}

{% block content %}

<div class="flex justify-center p-16">
    <h1 class="text-4xl font-bold">
        List Pertandingan

    </h1>
</div>

<div class="overflow-x-auto px-8 py-4">
    <table class="table table-zebra w-full border-2 border-primary-content rounded-md">
        <thead>
            <tr>
                <th >Tim 1</th>
                <th >Tim2</th>
                <th> </th>
              </tr>
        </thead>
        <tbody>
            <tr>
            
                <td>
                    {{tim_bertanding.0}}
                </td>
                <td>
                    {{tim_bertanding.1}}
                </td>
                <td class="text-center">
                    <a class="text-white font-regular py-2 px-4 rounded-md" style="background-color: #38404e;" href="{% url 'pembelian_tiket:pembelian_tiket' id_pertandingan=id_pertandingan %}">PILIH</a>
                </td>
            </tr>   
        </tbody>
        
    </table>
</div>



{% endblock content %}

pembelian_tiket/templates/list_waktu_stadium_tiket.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>List Waktu Stadium</title>
{% endblock meta %}

{% block content %}



<div class="flex justify-center p-16">
    <h1 class="text-4xl font-bold">
        List Waktu 
        {{ stadium }}
    </h1>
</div>

<div class="overflow-x-auto px-8 py-4">
    {% if list_pertandingan %}
        <table class="table table-zebra w-full border-2 border-primary-content rounded-md">
            <thead>
                <tr>
                    <th>List Waktu</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for waktu in list_pertandingan %}
                    <tr>
                        <td>{{ waktu.0 }} - {{ waktu.1 }}</td>
                        <td>
                            <a class="text-white font-regular py-2 px-4 rounded-md" style="background-color: #38404e;" href="{% url 'pembelian_tiket:list_pertandingan_tiket' waktu=date stadium=stadium %}">PESAN</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="flex justify-center items-center p-8">
            <p class="text-xl text-gray-500">Tidak ada pertandingan tersedia</p>
        </div>
    {% endif %}
</div>

{% endblock content %}

pembelian_tiket/templates/pembelian_tiket.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Beli Tiket</title>
{% endblock meta %}

{% block content %}
<div class="flex justify-center p-16">
    <h1 class="text-4xl font-bold">
        Beli Tiket
    </h1>
</div>

<div class="overflow-x-auto px-8 py-4" style="margin: 0 auto; width: fit-content; border: 1px solid white; border-radius: 10px;">
    <form method="post">
        {% csrf_token %}
        <label for="jenis_tiket">Jenis Tiket:</label>
        <select id="jenis_tiket" name="jenis_tiket" style="background-color: transparent; border: 1px solid #38404e; border-radius: 2px;">
            <option value="VIP">VIP</option>
            <option value="Main East">Main East</option>
            <option value="Kategori 1">Kategori 1</option>
            <option value="Kategori 2">Kategori 2</option>
        </select>
        <br><br>
        <label for="Pembayaran">Pembayaran:</label>
        <select id="Pembayaran" name="Pembayaran" style="background-color: transparent; border: 1px solid #38404e; border-radius: 2px;">
            <option value="OVO">OVO</option>
            <option value="GoPay">GoPay</option>
            <option value="ShopeePay">ShopeePay</option>
        </select>
        <br><br>
        <div class="flex justify-center">
            <button type="submit" class="text-white font-regular py-2 px-4 rounded-md" style="background-color: #38404e;" href="{% url 'home:home' %}">PILIH</button>
        </div>
    </form>
    
    {% if messages %}
    <div class="text-red-500 mt-4">
            
        <p>{{ messages }}</p>
           
    </div>
    {% endif %}
</div>
{% endblock content %}

pembelian_tiket/templates/pilih_stadium_tiket.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Pilih Stadium</title>
{% endblock meta %}

{% block content %}
<div class="flex justify-center p-16">
    <h1 class="text-4xl font-bold">
        Pilih Stadium
    </h1>
</div>

<div class="overflow-x-auto px-8 py-4" style="margin: 0 auto; width: fit-content; border: 1px solid white; border-radius: 10px;">
    <form action="{% url 'pembelian_tiket:list_waktu_stadium_tiket' %}" method="POST">
        {% csrf_token %}
        <label for="stadium">Stadium:</label>
        <select id="stadium" name="stadium" style="background-color: transparent; border: 1px solid #38404e; border-radius: 2px;">
            {% for stadium in list_stadium %}
                <option value="{{ stadium }}">{{ stadium }}</option>
            {% endfor %}
        </select>
        <br><br>
        <label for="date">Tanggal:</label>
        <input type="date" id="date" name="date" style="background-color: transparent;" value="{{ today }}">
        <br><br>
        <div class="flex justify-center">
            <button type="submit" class="text-white font-regular py-2 px-4 rounded-md" style="background-color: #38404e;">NEXT</button>
        </div>
    </form>
</div>
{% endblock content %}