c11_uleague/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('manage_pertandingan/', include('manage_pertandingan.urls')),
    path('list_pertandingan/', include('list_pertandingan.urls')),
    path('history_rapat/', include('history_rapat.urls')),
    path('pembuatan_pertandingan/', include('pembuatan_pertandingan.urls')),
    path('peminjaman_stadium/', include('peminjaman_stadium.urls')),
    path('pembelian_tiket/', include('pembelian_tiket.urls')),
    path('mulai_rapat/', include('mulai_rapat.urls')),
    path('mengelola_tim/', include('mengelola_tim.urls')),
    path('user_dashboard/', include('user_dashboard.urls')),
]

home/urls.py
from django.urls import path
from home.views import *

app_name = 'home'

urlpatterns = [
    path('', home, name='home'),
    path('login_register/', login_register, name='login_register'),
    path('register/', register, name='register'),
    path('register_manajer/', register_manajer, name='register_manajer'),
    path('register_penonton/', register_penonton, name='register_penonton'),
    path('register_panitia/', register_panitia, name='register_panitia'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
]

manage_pertandingan/urls.py
from django.urls import path
from manage_pertandingan.views import manage_pertandingan

app_name = 'manage_pertandingan'

urlpatterns = [
    path('', manage_pertandingan, name='manage_pertandingan'),
]

manage_pertandingan/models.py
from django.db import models

# Create your models here.

manage_pertandingan/views.py
import re
from django.shortcuts import redirect, render
from utils.query import query


# Create your views here.
#def manage_pertandingan(request):
#    return render(request, 'manage_pertandingan.html')

def manage_pertandingan(request):
    role = request.COOKIES.get('role')

    if role == None:
        return redirect('home:login')
    if role != "PANITIA":
        return redirect('home:home')
    
    month_translations = {
    "January": "Januari",
    "February": "Februari",
    "March": "Maret",
    "April": "April",
    "May": "Mei",
    "June": "Juni",
    "July": "Juli",
    "August": "Agustus",
    "September": "September",
    "October": "Oktober",
    "November": "November",
    "December": "Desember"
    }
    
    list_pertandingan, err = query("select * from pertandingan")
    # print(type(list_pertandingan))
    info_pertandingan = []
    for i in range(len(list_pertandingan)):

        tim, err = query(f"select distinct tm.nama_tim from tim_pertandingan tm, pertandingan p where tm.id_pertandingan = '{list_pertandingan[i][0]}'  ")

        tim = f"{tim[0][0]} vs {tim[1][0]}"

        stadium, err = query(f"select distinct s.nama from stadium s, pertandingan p where s.id_stadium = '{list_pertandingan[i][3]}' ")

        stadium = stadium[0][0]

        waktu = list_pertandingan[i][1]
        waktu = waktu.strftime("%d %B %Y, %H:%M")
        
        for month in month_translations:
            if month in waktu:
                translated_month = month_translations[month]
                waktu = re.sub(r'\b{}\b'.format(month), translated_month, waktu)
                    
        id_pertandingan = list_pertandingan[i][0]

        info_pertandingan.append([id_pertandingan, tim, stadium, waktu])
    
    context = {
        "info_pertandingan": info_pertandingan,
        "role": role
    }
    
    return render(request, 'manage_pertandingan.html', context)


""" def manage_pertandingan(request):
    role = request.COOKIES.get('role')

    if role == None:
        return redirect('home:login')
    if role != "PANITIA":
        return redirect('home:home')
    
    context = {
        "role": role
    }

    
    return render(request, 'manage_pertandingan.html', context) """

manage_pertandingan/templates/manage_pertandingan.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Manage Pertandingan</title>
<style>
  td, th, tr {
    text-align: center;
  }
</style>

{% endblock meta %}

{% block content %}
<div class="flex justify-center p-16">
    <h1 class="text-4xl font-bold">
        Manage Pertandingan
    </h1>
</div>
<!-- <div class="flex justify-center">
    <div class="text-sm breadcrumbs">
        <ul>
          <li><a>Home</a></li> 
          <li><a>Documents</a></li> 
          <li>Add Document</li>
        </ul>
      </div>
</div> -->
<div class="flex justify-center">
  <div class="btn-group">
    <a href='#slide1' class="btn btn-active">Stage 1</a>
    <a href='#slide2' class="btn">Stage 2</a>
    <a href='#slide3' class="btn">Final Stage</a>
  </div>
</div>
<div class="overflow-x-auto px-24 py-4 pb-8">
  <div class="carousel w-full shadow-xl rounded-lg">
    <div id="slide1" class="carousel-item relative w-full">
      <table class="table table-zebra w-full rounded-lg">
        <!-- head -->
        <thead>
          <tr>
            <!-- <th class="bg-base-300">Group</th> -->
            <th class="bg-base-300">Tim</th>
            <th class="bg-base-300">Waktu</th>
            <th class="bg-base-300">Pemenang</th>
            <th class="bg-base-300">Action</th>
          </tr>
        </thead>
        <tbody>
          <!-- row 1
          <tr>
            <th rowspan="2">A</th>
            <td>A VS B</td>
            <td>28 April 2023, 13:00</td>
            <td>A</td>
            <td><label for="modal1" class="btn btn-primary btn-sm">Lihat Peristiwa Tim 1</label>
            </br>
            </br>
              <button class="btn btn-primary btn-sm">Lihat Peristiwa Tim 2</button>
            </td>
          </tr>
          row 2
          <tr>
            <td>C VS D</td>
            <td>29 April 2023, 13:00</td>
            <td>D</td>
            <td><button class="btn btn-primary btn-sm">Lihat Peristiwa Tim 1</button>
            </br>
            </br>
              <button class="btn btn-primary btn-sm">Lihat Peristiwa Tim 2</button>
            </td>
          </tr>
          row 3
          <tr>
            <th rowspan="2">B</th>
            <td>E VS F</td>
            <td>[Waktu Dimulai - 5 Menit]</td>
            <td>-</td>
            <td><button class="btn btn-primary btn-sm">Mulai</button>
            </td>
          </tr>
          row 4
          <tr>
            <td>G VS H</td>
            <td>10 May 2023, 12:00</td>
            <td>-</td>
            <td><button class="btn btn-primary btn-sm" disabled="disabled">Belum dimulai</button>
            </td>
          </tr> -->
          
        </tbody>

        {% for data in info_pertandingan %}
        <tr>
          <td>{{data.1}}</td>
          <td>{{data.2}}</td>
          <td>{{data.3}}</td>
          <td><s href="{% url 'manage_pertandingan:manage_pertandingan' %}"><button type="button" class="btn btn-primary">Lihat Peristiwa Tim 1</button></a></td>

        </tr>
        <thead>
          <td colspan="5" class="bg-base-300"><button class="btn btn-primary btn-wide btn-sm">Finish</button></th>
      </thead>
      </table>
    </div>

    <div id="slide2" class="carousel-item relative w-full">
      <table class="table table-zebra w-full rounded-lg">
        <!-- head -->
        <thead>
          <tr>
           <!--  <th class="bg-base-300">Group</th> -->
            <th class="bg-base-300">Tim</th>
            <th class="bg-base-300">Waktu</th>
            <th class="bg-base-300">Pemenang</th>
            <th class="bg-base-300">Action</th>
          </tr>
        </thead>
        <tbody>
          <!-- row 1
          <tr>
            <th rowspan="2">A</th>
            <td>A VS B</td>
            <td>28 April 2023, 13:00</td>
            <td>A</td>
            <td>
              <button class="btn btn-primary btn-sm">Update</button>
            </td>
          </tr>
          row 2
          <tr>
            <td>C VS D</td>
            <td>29 April 2023, 13:00</td>
            <td>D</td>
            <td>
              <button class="btn btn-primary btn-sm">Update</button>
            </td>
          </tr>
          row 3
          <tr>
            <th rowspan="2">B</th>
            <td>E VS F</td>
            <td>-</td>
            <td>-</td>
            <td><button class="btn btn-primary btn-sm">Update</button>
            </td>
          </tr>
          row 4
          <tr>
            <td>G VS H</td>
            <td>10 May 2023, 12:00</td>
            <td>-</td>
            <td><button class="btn btn-primary btn-sm">Update</button>
            </td>
          </tr> -->
          {% for data in info_pertandingan %}
          <tr>
            <td>{{data.1}}</td>
            <td>{{data.2}}</td>
            <td>{{data.3}}</td>
            <td><s href="{% url 'manage_pertandingan:manage_pertandingan' %}"><button type="button" class="btn btn-primary">Update</button></a></td>
          </tr>
        </tbody>
        <thead>
            <td colspan="5" class="bg-base-300"><button class="btn btn-primary btn-wide btn-sm">Save</button></th>
        </thead>
      </table>
    </div>
    
    <div id="slide3" class="carousel-item relative w-full">
      <table class="table table-zebra w-full rounded-lg">
        <!-- head -->
        <thead>
          <tr>
            <!-- <th class="bg-base-300">Group</th> -->
            <th class="bg-base-300">Tim</th>
            <th class="bg-base-300">Waktu</th>
            <th class="bg-base-300">Pemenang</th>
            <th class="bg-base-300">Action</th>
          </tr>
        </thead>
        <tbody>
          <!-- row 1
          <tr>
            <th rowspan="2">A</th>
            <td>A VS B</td>
            <td>28 April 2023, 13:00</td>
            <td>A</td>
            <td><button class="btn btn-primary btn-sm">Lihat Peristiwa Tim 1</button>
            </br>
            </br>
              <button class="btn btn-primary btn-sm">Lihat Peristiwa Tim 2</button>
            </td>
          </tr>
          row 2
          <tr>
            <td>C VS D</td>
            <td>29 April 2023, 13:00</td>
            <td>D</td>
            <td><button class="btn btn-primary btn-sm">Lihat Peristiwa Tim 1</button>
            </br>
            </br>
              <button class="btn btn-primary btn-sm">Lihat Peristiwa Tim 2</button>
            </td>
          </tr>
          row 3
          <tr>
            <th rowspan="2">B</th>
            <td>E VS F</td>
            <td>[Waktu Dimulai - 5 Menit]</td>
            <td>-</td>
            <td><button class="btn btn-primary btn-sm">Mulai</button>
            </td>
          </tr>
          row 4
          <tr>
            <td>G VS H</td>
            <td>10 May 2023, 12:00</td>
            <td>-</td>
            <td><button class="btn btn-primary btn-sm" disabled="disabled">Belum dimulai</button>
            </td>
          </tr> -->
          {% for data in info_pertandingan %}
        <tr>
          <td>{{data.1}}</td>
          <td>{{data.2}}</td>
          <td>{{data.3}}</td>
          <td><s href="{% url 'manage_pertandingan:manage_pertandingan' %}"><button type="button" class="btn btn-primary">Lihat Peristiwa Tim 1</button></a></td>
        </tr>
        </tbody>
        <thead>
          <td colspan="5" class="bg-base-300"><button class="btn btn-primary btn-wide btn-sm">Finish</button></th>
      </thead>
      </table>
    </div>
  </div>
  </div>

<input type="checkbox" id="modal1" class="modal-toggle" />
<div class="modal">
  <div class="modal-box">
    <h3 class="font-bold text-lg pb-4">Peristiwa Tim A</h3>
    <table class="table table-zebra w-full rounded-md">
      <thead>
        <tr>
          <th class="bg-base-300">Nama Pemain</th>
          <th class="bg-base-300">Peristiwa</th>
        </tr>
      </thead>
      <tbody>
        <!-- <tr>
          <td>Nur</td>
          <td>Goal</td>
        </tr>
        <tr>
          <td>Fajar</td>
          <td>Goal</td>
        </tr> -->
        {% for data in info_pertandingan %}
        <tr>
          <td>{{data.1}}</td>
          <td>{{data.2}}</td>
        </tr>
      </tbody>
      <thead>
        <tr>
          <th colspan="2" class="bg-base-300"></th>
        </tr>
      </thead>
    </table>
    <div class="modal-action">
      <label for="modal1" class="btn">Yay!</label>
    </div>
  </div>
</div>
{% endblock content %}