c11_uleague/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('manage_pertandingan/', include('manage_pertandingan.urls')),
    path('list_pertandingan/', include('list_pertandingan.urls')),
    path('history_rapat/', include('history_rapat.urls')),
    path('pembuatan_pertandingan/', include('pembuatan_pertandingan.urls')),
    path('peminjaman_stadium/', include('peminjaman_stadium.urls')),
    path('pembelian_tiket/', include('pembelian_tiket.urls')),
    path('mulai_rapat/', include('mulai_rapat.urls')),
    path('mengelola_tim/', include('mengelola_tim.urls')),
    path('user_dashboard/', include('user_dashboard.urls')),
]

history_rapat/urls.py
from django.urls import path
from history_rapat.views import *

app_name = 'history_rapat'

urlpatterns = [
    path('', history_rapat, name='history_rapat'),
    path('isi_rapat/<str:isi>/', isi_rapat, name='isi_rapat')
]

home/urls.py
from django.urls import path
from home.views import *

app_name = 'home'

urlpatterns = [
    path('', home, name='home'),
    path('login_register/', login_register, name='login_register'),
    path('register/', register, name='register'),
    path('register_manajer/', register_manajer, name='register_manajer'),
    path('register_penonton/', register_penonton, name='register_penonton'),
    path('register_panitia/', register_panitia, name='register_panitia'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
]

mengelola_tim/urls.py
from django.urls import path
from mengelola_tim.views import form_daftar_tim, list_tim, daftar_pelatih, daftar_pemain

app_name = 'mengelola_tim'

urlpatterns = [
    path('', form_daftar_tim, name='form_daftar_tim'),
    path('list_tim', list_tim, name='list_tim'),
    path('daftar_pelatih', daftar_pelatih, name='daftar_pelatih'),
    path('daftar_pemain', daftar_pemain, name='daftar_pemain'),
]

mulai_rapat/urls.py
from django.urls import path
from mulai_rapat.views import pilih_pertandingan, rapat_pertandingan
app_name = 'mulai_rapat'

urlpatterns = [
    path('', pilih_pertandingan, name='pilih_pertandingan'),
    path('rapat_pertandingan/<uuid:id>', rapat_pertandingan, name='rapat_pertandingan'),

]

user_dashboard/urls.py
from django.urls import path
from user_dashboard.views import manajer_dashboard, panitia_dashboard, penonton_dashboard

app_name = 'user_dashboard'

urlpatterns = [
    path('manajer_dashboard/', manajer_dashboard, name='manajer_dashboard'),
    path('panitia_dashboard/', panitia_dashboard, name='panitia_dashboard'),
    path('penonton_dashboard/', penonton_dashboard, name='penonton_dashboard'),
]

templates/base.html
<!-- Copas dari repo pbp fajar-->
{% load static %}
<!DOCTYPE html>
<html lang="en" data-theme="emerald">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/daisyui@2.51.6/dist/full.css" rel="stylesheet" type="text/css" />
  <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2/dist/tailwind.min.css" rel="stylesheet" type="text/css" />
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;700&display=swap" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  {% block meta %}
  {% endblock meta %}
</head>

<body class="bg-base-200 w-full min-h-screen ">
    <div class="navbar bg-base-100 w-full">
      <div class="navbar-start">

    <!-- Mobile -->
      <div class="dropdown">
        <label tabindex="0" class="btn btn-ghost lg:hidden">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h8m-8 6h16" /></svg>
        </label>
        <ul tabindex="0" class="menu menu-compact dropdown-content mt-3 p-2 shadow bg-base-100 rounded-box w-52">
          {% if role == 'MANAJER' %}
          <li><a href="{% url 'home:home' %}">Dashboard</a></li>
          <li><a href="{% url 'mengelola_tim:form_daftar_tim' %}">Mengelola Tim</a></li>
          <li><a href="{% url 'user_dashboard:manajer_dashboard' %}">Dashboard</a></li>
          <li><a href="{% url 'peminjaman_stadium:peminjaman_stadium' %}">Peminjaman Stadium</a></li>
          <li><a href="{% url 'list_pertandingan:list_pertandingan' %}">List Pertandingan</a></li>
          <li><a href="{% url 'history_rapat:history_rapat' %}">History Rapat</a></li>
          {% elif role == 'PENONTON' %}
          <li><a  href="{% url 'user_dashboard:penonton_dashboard' %}">Dashboard</a></li>
          <li><a href="{% url 'pembelian_tiket:pilih_stadium_tiket' %}">Pembelian Tiket</a></li>
          <li><a href="{% url 'list_pertandingan:list_pertandingan' %}">List Pertandingan</a></li>
          {% elif role == 'PANITIA' %}
          <li><a href="{% url 'user_dashboard:panitia_dashboard' %}">Dashboard</a></li>
          <li><a href="{% url 'mulai_rapat:pilih_pertandingan' %}">Rapat</a></li>
          <li><a href="{% url 'manage_pertandingan:manage_pertandingan' %}">Manage Pertandingan</a></li>
          {% endif %} 
        </ul>
      </div>
      <a class="btn btn-ghost normal-case text-xl" href="{% url 'home:home' %}">U-League</a>
    </div>

    <!-- Desktop -->
    <div class="navbar-center hidden lg:flex" style="z-index: 9999;">
      <ul class="menu menu-horizontal px-1">

        {% if role == 'MANAJER' %}
        <li><a href="{% url 'home:home' %}">Dashboard</a></li>
        <li><a href="{% url 'mengelola_tim:form_daftar_tim' %}">Mengelola Tim</a></li>
        <li><a href="{% url 'user_dashboard:manajer_dashboard' %}">Dashboard</a></li>
        <li><a href="{% url 'peminjaman_stadium:peminjaman_stadium' %}">Peminjaman Stadium</a></li>
        <li><a href="{% url 'list_pertandingan:list_pertandingan' %}">List Pertandingan</a></li>
        <li><a href="{% url 'history_rapat:history_rapat' %}">History Rapat</a></li>

        {% elif role == 'PENONTON' %}
        <li><a  href="{% url 'user_dashboard:penonton_dashboard' %}">Dashboard</a></li>
        <li><a href="{% url 'pembelian_tiket:pilih_stadium_tiket' %}">Pembelian Tiket</a></li>
        <li><a href="{% url 'list_pertandingan:list_pertandingan' %}">List Pertandingan</a></li>

        {% elif role == 'PANITIA' %}
        <li><a href="{% url 'user_dashboard:panitia_dashboard' %}"">Dashboard</a></li>
        <li><a href="{% url 'mulai_rapat:pilih_pertandingan' %}">Rapat</a></li>
        <li><a href="{% url 'manage_pertandingan:manage_pertandingan' %}">Manage Pertandingan</a></li>
        {% endif %} 
      </ul>
    </div>
       
    <div class="navbar-end">
      {% if role is None %}
      <a class="btn" href ="{% url 'home:login' %}">Login</a>
      {% else %}
      <a class="btn" href ="{% url 'home:logout' %}">Logout</a>
      {% endif %}
    </div>
    
  </div>

  {% block content %}
  {% endblock content %}
  <footer class="footer items-center p-4 bg-neutral text-neutral-content">
    <div class="items-center grid-flow-col">
      <svg width="36" height="36" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd" clip-rule="evenodd" class="fill-current"><path d="M22.672 15.226l-2.432.811.841 2.515c.33 1.019-.209 2.127-1.23 2.456-1.15.325-2.148-.321-2.463-1.226l-.84-2.518-5.013 1.677.84 2.517c.391 1.203-.434 2.542-1.831 2.542-.88 0-1.601-.564-1.86-1.314l-.842-2.516-2.431.809c-1.135.328-2.145-.317-2.463-1.229-.329-1.018.211-2.127 1.231-2.456l2.432-.809-1.621-4.823-2.432.808c-1.355.384-2.558-.59-2.558-1.839 0-.817.509-1.582 1.327-1.846l2.433-.809-.842-2.515c-.33-1.02.211-2.129 1.232-2.458 1.02-.329 2.13.209 2.461 1.229l.842 2.515 5.011-1.677-.839-2.517c-.403-1.238.484-2.553 1.843-2.553.819 0 1.585.509 1.85 1.326l.841 2.517 2.431-.81c1.02-.33 2.131.211 2.461 1.229.332 1.018-.21 2.126-1.23 2.456l-2.433.809 1.622 4.823 2.433-.809c1.242-.401 2.557.484 2.557 1.838 0 .819-.51 1.583-1.328 1.847m-8.992-6.428l-5.01 1.675 1.619 4.828 5.011-1.674-1.62-4.829z"></path></svg> 
      <p>Copyright © 2023 Basdat C10 - All right reserved</p>
    </div> 
    <div class="grid-flow-col gap-4 md:place-self-center md:justify-self-end">
      <a><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current"><path d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"></path></svg>
      </a> 
      <a><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current"><path d="M19.615 3.184c-3.604-.246-11.631-.245-15.23 0-3.897.266-4.356 2.62-4.385 8.816.029 6.185.484 8.549 4.385 8.816 3.6.245 11.626.246 15.23 0 3.897-.266 4.356-2.62 4.385-8.816-.029-6.185-.484-8.549-4.385-8.816zm-10.615 12.816v-8l8 3.993-8 4.007z"></path></svg></a>
      <a><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current"><path d="M9 8h-3v4h3v12h5v-12h3.642l.358-4h-4v-1.667c0-.955.192-1.333 1.115-1.333h2.885v-5h-3.808c-3.596 0-5.192 1.583-5.192 4.615v3.385z"></path></svg></a>
    </div>
  </footer>
</body>

</html>